run:
  timeout: 5m
linters:
  enable-all: true
  disable:
    - funlen
    - gochecknoglobals
    - dupl
    - wsl
    - gomnd
linters-settings:
  gocyclo:
    # minimal code complexity to report, 30 by default
    min-complexity: 50
  gocognit:
    # minimal code complexity to report, 30 by default
    min-complexity: 110
issues:
  exclude-rules:
    - text: "Use of ssh InsecureIgnoreHostKey"
      linters:
        - gosec
    - text: "`jnpr` can be `github.com/hashicorp/terraform-plugin-sdk/terraform.ResourceProviderCloser`"
      linters:
        - interfacer
