run:
  timeout: 5m
linters:
  enable-all: true
  disable:
    - maligned # deprecated
    - scopelint # deprecated
    - interfacer # deprecated
    - funlen
    - gochecknoglobals
    - dupl
    - wsl
    - gomnd
    - goerr113 
    - nestif
    - gofumpt
    - exhaustivestruct
    - paralleltest
    - gci
    - cyclop
    - forcetypeassert
linters-settings:
  gocyclo:
    # minimal code complexity to report, 30 by default
    min-complexity: 90
  gocognit:
    # minimal code complexity to report, 30 by default
    min-complexity: 180
issues:
  exclude-rules:
    - text: "Use of ssh InsecureIgnoreHostKey"
      linters:
        - gosec
    - text: "`jnpr` can be `io.Closer`"
      linters:
        - interfacer
