run:
  timeout: 5m
linters:
  enable-all: true
  disable:
    # maligned # deprecated 1.38 but govet-fieldalignment not usuable
    - interfacer # deprecated 1.38
    - scopelint # deprecated 1.39
    - golint # deprecated 1.41
    - exhaustivestruct # deprecated 1.46
    - funlen
    - dupl
    - wsl
    - gomnd
    - goerr113 
    - nestif
    - exhaustruct
    - paralleltest
    - gci
    - cyclop
    - forcetypeassert
    - gomoddirectives
    - varnamelen
    - nonamedreturns
    - maintidx
    - execinquery
linters-settings:
  gocognit:
    # minimal code complexity to report, 30 by default
    min-complexity: 180
  goconst:
    # Minimum occurrences of constant string count to trigger issue.
    min-occurrences: 10
    # Ignore test files.
    ignore-tests: true
  gocyclo:
    # minimal code complexity to report, 30 by default
    min-complexity: 90
  gofumpt:
    # Choose whether to use the extra rules.
    extra-rules: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
issues:
  exclude-rules:
    - text: "Use of ssh InsecureIgnoreHostKey"
      linters:
        - gosec
   