linters:
  enable-all: true
  disable:
    - funlen
    - gochecknoglobals
    - dupl
linters-settings:
  gocyclo:
    # minimal code complexity to report, 30 by default
    min-complexity: 50
issues:
  exclude-rules:
    - text: "Use of ssh InsecureIgnoreHostKey"
      linters:
        - gosec
    - text: "`jnpr` can be `github.com/hashicorp/terraform/terraform.ResourceProviderCloser`"
      linters:
        - interfacer 
