package providerfwk_test

import (
	"os"
	"testing"

	"github.com/jeremmfr/terraform-provider-junos/internal/junos"

	"github.com/hashicorp/terraform-plugin-testing/config"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

// export TESTACC_INTERFACE=<inteface> for choose interface available else it's ge-0/0/3.
func TestAccResourceSecurity_basic(t *testing.T) {
	testaccInterface := junos.DefaultInterfaceTestAcc
	if iface := os.Getenv("TESTACC_INTERFACE"); iface != "" {
		testaccInterface = iface
	}
	if os.Getenv("TESTACC_SRX") != "" {
		resource.Test(t, resource.TestCase{
			PreCheck:                 func() { testAccPreCheck(t) },
			ProtoV5ProviderFactories: testAccProtoV5ProviderFactories,
			Steps: []resource.TestStep{
				{
					ConfigDirectory: config.TestStepDirectory(),
				},
				{
					ConfigDirectory: config.TestStepDirectory(),
					ConfigVariables: map[string]config.Variable{
						"interface": config.StringVariable(testaccInterface),
					},
					Check: resource.ComposeTestCheckFunc(
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"flow.advanced_options.drop_matching_reserved_ip_address", "true"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"flow.advanced_options.drop_matching_link_local_address", "true"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"flow.advanced_options.reverse_route_packet_mode_vr", "true"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"flow.aging.early_ageout", "10"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"flow.aging.high_watermark", "90"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"flow.aging.low_watermark", "80"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"flow.allow_dns_reply", "true"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"flow.allow_embedded_icmp", "true"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"flow.allow_reverse_ecmp", "true"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"flow.enable_reroute_uniform_link_check_nat", "true"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"flow.ethernet_switching.block_non_ip_all", "true"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"flow.ethernet_switching.bpdu_vlan_flooding", "true"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"flow.force_ip_reassembly", "true"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"flow.ipsec_performance_acceleration", "true"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"flow.mcast_buffer_enhance", "true"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"flow.pending_sess_queue_length", "normal"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"flow.preserve_incoming_fragment_size", "true"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"flow.route_change_timeout", "10"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"flow.syn_flood_protection_mode", "syn-proxy"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"flow.sync_icmp_session", "true"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"flow.tcp_mss.all_tcp_mss", "1499"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"flow.tcp_session.fin_invalidate_session", "true"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"flow.tcp_session.maximum_window", "512K"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"flow.tcp_session.no_sequence_check", "true"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"flow.tcp_session.rst_invalidate_session", "true"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"flow.tcp_session.rst_sequence_check", "true"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"flow.tcp_session.strict_syn_check", "true"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"flow.tcp_session.tcp_initial_timeout", "10"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"forwarding_options.mpls_mode", "flow-based"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"forwarding_options.inet6_mode", "flow-based"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"forwarding_options.iso_mode_packet_based", "true"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"ike_traceoptions.file.name", "ike.log"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"ike_traceoptions.file.files", "5"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"ike_traceoptions.file.match", "test"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"ike_traceoptions.file.size", "102400"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"ike_traceoptions.file.world_readable", "true"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"ike_traceoptions.flag.#", "1"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"ike_traceoptions.flag.0", "all"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"ike_traceoptions.rate_limit", "100"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"ike_traceoptions.no_remote_trace", "true"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"log.disable", "true"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"log.facility_override", "local7"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"log.file.files", "10"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"log.file.name", "security.log"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"log.file.path", "/"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"log.file.size", "10"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"log.format", "syslog"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"log.mode", "event"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"log.report", "true"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"log.source_interface", testaccInterface+".0"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"log.transport.protocol", "tcp"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"log.transport.tcp_connections", "5"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"log.transport.tls_profile", "testacc_security"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"log.utc_timestamp", "true"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"policies.policy_rematch", "true"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"utm.feature_profile_web_filtering_type", "juniper-enhanced"),
					),
				},
				{
					ConfigVariables: map[string]config.Variable{
						"interface": config.StringVariable(testaccInterface),
					},
					ResourceName:      "junos_security.testacc_security",
					ImportState:       true,
					ImportStateVerify: true,
				},
				{
					ConfigDirectory: config.TestStepDirectory(),
					Check: resource.ComposeTestCheckFunc(
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"flow.ethernet_switching.bypass_non_ip_unicast", "true"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"flow.ethernet_switching.no_packet_flooding.no_trace_route", "true"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"flow.tcp_mss.gre_in.mss", "1399"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"flow.tcp_mss.gre_out.mss", "1399"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"flow.tcp_mss.ipsec_vpn.mss", "1399"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"flow.tcp_session.no_syn_check", "true"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"flow.tcp_session.no_syn_check_in_tunnel", "true"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"flow.tcp_session.time_wait_state.apply_to_half_close_state", "true"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"flow.tcp_session.time_wait_state.session_ageout", "true"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"ike_traceoptions.file.no_world_readable", "true"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"ike_traceoptions.flag.#", "0"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"log.event_rate", "100"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"log.max_database_record", "1000"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"log.rate_cap", "100"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"log.source_address", "192.0.2.1"),
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"policies.policy_rematch_extensive", "true"),
					),
				},
				{
					ConfigDirectory: config.TestStepDirectory(),
					Check: resource.ComposeTestCheckFunc(
						resource.TestCheckResourceAttr("junos_security.testacc_security",
							"flow.tcp_session.time_wait_state.session_timeout", "90"),
					),
				},
				{
					ConfigDirectory: config.TestStepDirectory(),
				},
			},
		})
	}
}
