package providerfwk_test

import (
	"os"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/config"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/plancheck"
	"github.com/hashicorp/terraform-plugin-testing/tfjsonpath"
)

func TestAccResourceBgpNeighbor_basic(t *testing.T) {
	if os.Getenv("TESTACC_SWITCH") == "" {
		resource.Test(t, resource.TestCase{
			PreCheck:                 func() { testAccPreCheck(t) },
			ProtoV5ProviderFactories: testAccProtoV5ProviderFactories,
			Steps: []resource.TestStep{
				{
					ConfigDirectory: config.TestStepDirectory(),
					Check: resource.ComposeTestCheckFunc(
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"routing_instance", "testacc_bgpneighbor"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"group", "testacc_bgpneighbor"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"advertise_inactive", "true"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"advertise_peer_as", "true"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"as_override", "true"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"cluster", "192.0.2.3"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"damping", "true"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"log_updown", "true"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"mtu_discovery", "true"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"remove_private", "true"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"passive", "true"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"hold_time", "30"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"local_as", "65001"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"local_as_private", "true"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"local_as_loops", "1"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"local_preference", "100"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"metric_out", "100"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"out_delay", "30"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"peer_as", "65002"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"preference", "100"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"authentication_algorithm", "md5"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"local_address", "192.0.2.3"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"export.#", "1"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"export.0", "testacc_bgpneighbor"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"import.#", "1"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"import.0", "testacc_bgpneighbor"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"bfd_liveness_detection.detection_time_threshold", "60"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"bfd_liveness_detection.transmit_interval_threshold", "30"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"bfd_liveness_detection.transmit_interval_minimum_interval", "10"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"bfd_liveness_detection.holddown_interval", "10"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"bfd_liveness_detection.minimum_interval", "10"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"bfd_liveness_detection.minimum_receive_interval", "10"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"bfd_liveness_detection.multiplier", "2"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"bfd_liveness_detection.session_mode", "automatic"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"family_inet.#", "2"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"family_inet.0.nlri_type", "unicast"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"family_inet.0.accepted_prefix_limit.maximum", "2"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"family_inet.0.accepted_prefix_limit.teardown", "50"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"family_inet.0.accepted_prefix_limit.teardown_idle_timeout", "30"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"family_inet.0.prefix_limit.maximum", "2"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"family_inet.0.prefix_limit.teardown", "50"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"family_inet.0.prefix_limit.teardown_idle_timeout", "30"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"family_inet.1.nlri_type", "multicast"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"family_inet.1.accepted_prefix_limit.teardown_idle_timeout_forever", "true"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"family_inet.1.prefix_limit.teardown_idle_timeout_forever", "true"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"family_inet6.#", "2"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"graceful_restart.disable", "true"),
					),
				},
				{
					ResourceName:      "junos_bgp_neighbor.testacc_bgpneighbor",
					ImportState:       true,
					ImportStateVerify: true,
				},
				{
					ConfigDirectory: config.TestStepDirectory(),
					ConfigPlanChecks: resource.ConfigPlanChecks{
						PreApply: []plancheck.PlanCheck{
							plancheck.ExpectSensitiveValue("junos_bgp_neighbor.testacc_bgpneighbor",
								tfjsonpath.New("authentication_key")),
						},
					},
					Check: resource.ComposeTestCheckFunc(
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"routing_instance", "testacc_bgpneighbor"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"group", "testacc_bgpneighbor"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"advertise_external_conditional", "true"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"bgp_multipath.multiple_as", "true"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"no_advertise_peer_as", "true"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"metric_out_igp_offset", "-10"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"metric_out_igp_delay_med_update", "true"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"authentication_key", "password"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"graceful_restart.restart_time", "10"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor",
							"graceful_restart.stale_route_time", "10"),
					),
				},
				{
					ConfigDirectory: config.TestStepDirectory(),
					Check: resource.ComposeTestCheckFunc(
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor2",
							"advertise_external", "true"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor2",
							"accept_remote_nexthop", "true"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor2",
							"multihop", "true"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor2",
							"local_as_no_prepend_global_as", "true"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor2",
							"metric_out_minimum_igp_offset", "-10"),
					),
				},
				{
					ConfigDirectory: config.TestStepDirectory(),
					Check: resource.ComposeTestCheckFunc(
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor2",
							"local_as_alias", "true"),
						resource.TestCheckResourceAttr("junos_bgp_neighbor.testacc_bgpneighbor2",
							"metric_out_minimum_igp", "true"),
					),
				},
			},
		})
	}
}
