package providerfwk_test

import (
	"os"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/config"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccResourceFirewallFilter_basic(t *testing.T) {
	if os.Getenv("TESTACC_SWITCH") == "" {
		resource.Test(t, resource.TestCase{
			PreCheck:                 func() { testAccPreCheck(t) },
			ProtoV5ProviderFactories: testAccProtoV5ProviderFactories,
			Steps: []resource.TestStep{
				{
					ConfigDirectory: config.TestStepDirectory(),
					Check: resource.ComposeTestCheckFunc(
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter",
							"family", "inet"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter",
							"interface_specific", "true"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter",
							"term.#", "2"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter",
							"term.0.name", "testacc_fwFilter_term1"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter",
							"term.0.from.address.#", "1"),
						resource.TestCheckTypeSetElemAttr("junos_firewall_filter.testacc_fwFilter",
							"term.0.from.address.*", "192.0.2.0/25"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter",
							"term.0.from.address_except.#", "1"),
						resource.TestCheckTypeSetElemAttr("junos_firewall_filter.testacc_fwFilter",
							"term.0.from.address_except.*", "192.0.2.128/25"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter",
							"term.0.from.port.#", "1"),
						resource.TestCheckTypeSetElemAttr("junos_firewall_filter.testacc_fwFilter",
							"term.0.from.port.*", "22-23"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter",
							"term.0.from.prefix_list.#", "1"),
						resource.TestCheckTypeSetElemAttr("junos_firewall_filter.testacc_fwFilter",
							"term.0.from.prefix_list.*", "testacc_fwFilter#1"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter",
							"term.0.from.prefix_list_except.#", "1"),
						resource.TestCheckTypeSetElemAttr("junos_firewall_filter.testacc_fwFilter",
							"term.0.from.prefix_list_except.*", "testacc_fwFilter#2"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter",
							"term.0.from.protocol.#", "1"),
						resource.TestCheckTypeSetElemAttr("junos_firewall_filter.testacc_fwFilter",
							"term.0.from.protocol.*", "tcp"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter",
							"term.0.from.tcp_flags", "!0x3"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter",
							"term.0.from.is_fragment", "true"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter",
							"term.0.then.action", "next term"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter",
							"term.0.then.syslog", "true"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter",
							"term.0.then.log", "true"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter",
							"term.0.then.port_mirror", "true"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter",
							"term.0.then.service_accounting", "true"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter",
							"term.1.from.icmp_code.#", "1"),
						resource.TestCheckTypeSetElemAttr("junos_firewall_filter.testacc_fwFilter",
							"term.1.from.icmp_code.*", "network-unreachable"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter",
							"term.1.from.icmp_type.#", "1"),
						resource.TestCheckTypeSetElemAttr("junos_firewall_filter.testacc_fwFilter",
							"term.1.from.icmp_type.*", "router-advertisement"),
					),
				},
				{
					ConfigDirectory: config.TestStepDirectory(),
					Check: resource.ComposeTestCheckFunc(
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter",
							"term.#", "5"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter",
							"term.1.from.source_address.#", "1"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter",
							"term.1.from.source_address_except.#", "1"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter",
							"term.1.from.port_except.#", "1"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter",
							"term.1.from.source_prefix_list.#", "1"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter",
							"term.1.from.source_prefix_list_except.#", "1"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter",
							"term.1.from.tcp_established", "true"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter",
							"term.1.from.protocol_except.#", "1"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter",
							"term.1.then.policer", "testacc_fwfilter#1"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter",
							"term.1.then.action", "accept"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter",
							"term.2.from.destination_address.#", "1"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter",
							"term.2.from.destination_address_except.#", "1"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter",
							"term.2.from.destination_port.#", "1"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter",
							"term.2.from.source_port_except.#", "1"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter",
							"term.2.from.destination_prefix_list.#", "1"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter",
							"term.2.from.destination_prefix_list_except.#", "1"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter",
							"term.2.from.tcp_initial", "true"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter",
							"term.2.then.action", "discard"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter",
							"term.3.from.source_port.#", "1"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter",
							"term.3.from.destination_port_except.#", "1"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter",
							"term.3.then.action", "reject"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter",
							"term.4.from.icmp_code_except.#", "1"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter",
							"term.4.from.icmp_type_except.#", "1"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter6",
							"family", "inet6"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter6",
							"term.#", "1"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter6",
							"term.0.from.next_header.#", "1"),
						resource.TestCheckTypeSetElemAttr("junos_firewall_filter.testacc_fwFilter6",
							"term.0.from.next_header.*", "icmp6"),
						resource.TestCheckResourceAttr("junos_firewall_filter.testacc_fwFilter6",
							"term.0.then.action", "discard"),
					),
				},
				{
					ResourceName:      "junos_firewall_filter.testacc_fwFilter",
					ImportState:       true,
					ImportStateVerify: true,
				},
			},
		})
	}
}
