package junos

const (
	idSeparator           = "_-_"
	defaultWord           = "default"
	evpnWord              = "evpn"
	inetWord              = "inet"
	inet6Word             = "inet6"
	mplsWord              = "mpls"
	emptyWord             = "empty"
	matchWord             = "match"
	permitWord            = "permit"
	thenWord              = "then"
	prefixWord            = "prefix"
	prefixNameWord        = "prefix-name"
	actionNoneWord        = "none"
	addWord               = "add"
	deleteWord            = "delete"
	setWord               = "set"
	setLineStart          = setWord + " "
	st0Word               = "st0"
	ospfV2                = "ospf"
	ospfV3                = "ospf3"
	activeW               = "active"
	asPathAtomicAggregate = "as-path atomic-aggregate"
	passiveW              = "passive"
	discardW              = "discard"
	disableW              = "disable"
	dynamicDB             = "dynamic-db"
	preemptWord           = "preempt"
	flowControlWords      = "flow-control"
	noFlowControlWords    = "no-flow-control"
	loopbackWord          = "loopback"
	noLoopbackWord        = "no-loopback"
	actionCos             = "class-of-service"
	actionMarkDiffServ    = "mark-diffserv"
	localWord             = "local"
	privacyNoneWord       = "privacy-none"
)
