package provider_test

import (
	"os"
	"regexp"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/config"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/knownvalue"
	"github.com/hashicorp/terraform-plugin-testing/plancheck"
	"github.com/hashicorp/terraform-plugin-testing/statecheck"
	"github.com/hashicorp/terraform-plugin-testing/tfjsonpath"
	"github.com/hashicorp/terraform-plugin-testing/tfversion"
)

func TestAccResourceSystemRootAuthentication_basic(t *testing.T) {
	if os.Getenv("TESTACC_SWITCH") == "" {
		resource.Test(t, resource.TestCase{
			PreCheck: func() { testAccPreCheck(t) },
			Steps: []resource.TestStep{
				{
					ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
					ConfigDirectory:          config.TestStepDirectory(),
					Check: resource.ComposeTestCheckFunc(
						resource.TestCheckResourceAttr("junos_system_root_authentication.root_auth",
							"encrypted_password", "$6$XXXX"),
						resource.TestCheckResourceAttr("junos_system_root_authentication.root_auth",
							"ssh_public_keys.#", "1"),
					),
				},
				{
					ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
					ResourceName:             "junos_system_root_authentication.root_auth",
					ImportState:              true,
					ImportStateVerify:        true,
				},
				{
					ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
					ConfigDirectory:          config.TestStepDirectory(),
					Check: resource.ComposeTestCheckFunc(
						resource.TestCheckResourceAttr("junos_system_root_authentication.root_auth",
							"ssh_public_keys.#", "0"),
					),
				},
				{
					ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
					ConfigDirectory:          config.TestStepDirectory(),
					ExpectNonEmptyPlan:       true,
					ConfigPlanChecks: resource.ConfigPlanChecks{
						PostApplyPostRefresh: []plancheck.PlanCheck{
							plancheck.ExpectNonEmptyPlan(),
							plancheck.ExpectResourceAction(
								"junos_system_root_authentication.root_auth",
								plancheck.ResourceActionUpdate,
							),
							plancheck.ExpectResourceAction(
								"junos_system_root_authentication.root_auth_copy",
								plancheck.ResourceActionNoop,
							),
						},
					},
				},
				{
					ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
					ConfigDirectory:          config.TestStepDirectory(),
					ExpectNonEmptyPlan:       true,
					ConfigPlanChecks: resource.ConfigPlanChecks{
						PostApplyPostRefresh: []plancheck.PlanCheck{
							plancheck.ExpectNonEmptyPlan(),
							plancheck.ExpectResourceAction(
								"junos_system_root_authentication.root_auth",
								plancheck.ResourceActionNoop,
							),
							plancheck.ExpectResourceAction(
								"junos_system_root_authentication.root_auth_copy",
								plancheck.ResourceActionUpdate,
							),
						},
					},
				},
			},
		})
	}
}

func TestAccResourceSystemRootAuthentication_writeOnly(t *testing.T) {
	if os.Getenv("TESTACC_SWITCH") == "" {
		resource.Test(t, resource.TestCase{
			PreCheck:                 func() { testAccPreCheck(t) },
			ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
			TerraformVersionChecks: []tfversion.TerraformVersionCheck{
				tfversion.SkipBelow(tfversion.Version1_11_0),
			},
			Steps: []resource.TestStep{
				{
					ConfigDirectory: config.TestStepDirectory(),
					Check: resource.ComposeTestCheckFunc(
						resource.TestCheckNoResourceAttr("junos_system_root_authentication.root_auth_wo",
							"encrypted_password"),
						resource.TestCheckNoResourceAttr("junos_system_root_authentication.root_auth_wo",
							"encrypted_password_wo"),
						resource.TestCheckResourceAttr("junos_system_root_authentication.root_auth_wo",
							"encrypted_password_wo_version", "1"),
					),
				},
				{
					// check that the write-only password has really been sent to the device
					ConfigDirectory: config.TestStepDirectory(),
					ConfigStateChecks: []statecheck.StateCheck{
						statecheck.ExpectKnownValue(
							"data.junos_config_raw.root_auth_wo",
							tfjsonpath.New("config"),
							knownvalue.StringRegexp(regexp.MustCompile(
								`set system root-authentication encrypted-password `,
							)),
						),
					},
				},
				{
					ConfigDirectory: config.TestStepDirectory(),
					Check: resource.ComposeTestCheckFunc(
						resource.TestCheckNoResourceAttr("junos_system_root_authentication.root_auth_wo",
							"encrypted_password"),
						resource.TestCheckNoResourceAttr("junos_system_root_authentication.root_auth_wo",
							"encrypted_password_wo"),
						resource.TestCheckResourceAttr("junos_system_root_authentication.root_auth_wo",
							"encrypted_password_wo_version", "2"),
					),
				},
				{
					// switch to a write-only plain text password,
					// the encrypted password generated by the device must not be kept in the private state
					ConfigDirectory: config.TestStepDirectory(),
					Check: resource.ComposeTestCheckFunc(
						resource.TestCheckNoResourceAttr("junos_system_root_authentication.root_auth_wo",
							"encrypted_password"),
						resource.TestCheckNoResourceAttr("junos_system_root_authentication.root_auth_wo",
							"plain_text_password"),
						resource.TestCheckNoResourceAttr("junos_system_root_authentication.root_auth_wo",
							"plain_text_password_wo"),
						resource.TestCheckResourceAttr("junos_system_root_authentication.root_auth_wo",
							"plain_text_password_wo_version", "1"),
						resource.TestCheckNoResourceAttr("junos_system_root_authentication.root_auth_wo",
							"encrypted_password_wo_version"),
					),
				},
				{
					// the plain text password is unchanged, so the plan must stay empty
					// even though the provider cannot compare it with the device
					ConfigDirectory: config.TestStepDirectory(),
					ConfigPlanChecks: resource.ConfigPlanChecks{
						PreApply: []plancheck.PlanCheck{
							plancheck.ExpectEmptyPlan(),
						},
					},
				},
			},
		})
	}
}
